# This is a basic workflow to help you get started with Actions

name: CI-f1-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as 
    steps:
  - name: Setup cloudflared
    uses: AnimMouse/setup-cloudflared@v1
    with:
      cloudflare_tunnel_credential: ${{ secrets.CLOUDFLARE_TUNNEL_CREDENTIAL }}
      cloudflare_tunnel_configuration: ${{ secrets.CLOUDFLARE_TUNNEL_CONFIGURATION }}
      cloudflare_tunnel_id: ${{ secrets.CLOUDFLARE_TUNNEL_ID }}
      
    - name: Start Python HTTP server
      run: timeout 1m python -m http.server 8080 || true
      run: echo "salam man aliza hastam va dustam $USER"
      run: docker pull scottyhardy/docker-remote-desktop
      run: docker run -it -d --rm --hostname="$(hostname)" --publish="3389:3389/tcp" --name="remote-desktop" scottyhardy/docker-remote-desktop:latest /bin/bash
      run: python3 ./timer.py 3
      
    - name: Shutdown and view logs of cloudflared
      if: always()
      uses: AnimMouse/setup-cloudflared/
